// <auto-generated />
using System;
using GigLedger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GigLedger.Data.Migrations
{
    [DbContext(typeof(LedgerContext))]
    [Migration("20260926043151_TaxRecords")]
    partial class TaxRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GigLedger.Data.AttachmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "OwnerId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GigLedger.Data.ChargeSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Charger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostGrade")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndSoc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kwh")
                        .HasColumnType("TEXT");

                    b.Property<string>("KwhGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Odometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartSoc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChargeSessions");
                });

            modelBuilder.Entity("GigLedger.Data.DriveRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("GigLedger.Data.ExpenseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmountGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GigLedger.Data.HomeRateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PerKwh")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e771495-0000-4000-8000-000000000002"),
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            IsPlaceholder = true,
                            PerKwh = 0.15m,
                            RecordedAt = new DateTimeOffset(new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GigLedger.Data.MileageRateRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerMile")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MileageRates");
                });

            modelBuilder.Entity("GigLedger.Data.PlatformFormRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Monthly")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlatformForms");
                });

            modelBuilder.Entity("GigLedger.Data.SettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcceptThreshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultMilesPerKwh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultPricePerKwh")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e771495-0000-4000-8000-000000000001"),
                            AcceptThreshold = 25.00m,
                            DefaultMilesPerKwh = 4.0m,
                            DefaultPricePerKwh = 0.69m,
                            RecordedAt = new DateTimeOffset(new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GigLedger.Data.ShiftCloseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftCloses");
                });

            modelBuilder.Entity("GigLedger.Data.ShiftRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("GigLedger.Data.TipRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmountGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Tips");
                });

            modelBuilder.Entity("GigLedger.Data.TripActualsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElapsedMinutesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RouteMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripActuals");
                });

            modelBuilder.Entity("GigLedger.Data.TripRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Drops")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstimatedMinutesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Items")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OfferedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pay")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnMilesOverride")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StatedMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatedMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
