// <auto-generated />
using System;
using GigLedger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GigLedger.Data.Migrations
{
    [DbContext(typeof(LedgerContext))]
    [Migration("20260925200711_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GigLedger.Data.SettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcceptThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultMilesPerKwh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultPricePerKwh")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("GigLedger.Data.ShiftCloseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EndOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftCloses");
                });

            modelBuilder.Entity("GigLedger.Data.ShiftRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartOdometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartOdometerGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("GigLedger.Data.TripActualsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElapsedMinutesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReturnMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RouteMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TripId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripActuals");
                });

            modelBuilder.Entity("GigLedger.Data.TripRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Drops")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstimatedMinutesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Items")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OfferedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pay")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnMilesOverride")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StatedMiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatedMilesGrade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
